server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
